### ISSUE TITLE
One WorkSpace

### ISSUE THREAD

**Issue by riyan-dcosta** [riyan-dcosta/learn-python#2]
Currently we may have different python versions and may also have different OS in future. Must need to find a best approach so there wont be any runtime failures.

## Some options to run as container
 - [x] Docker container 
 - [x] VS Code Dev Containers
 - [x] Option to host the container in Server
 - [x] Ease of use for instalation, setup and git push in the containers.

**Comment by riyan-dcosta** [comment]
Used Docker to get python 3.11.4-slim image.
Need to Install Docker in local machine and execute `docker build --tag python-docker .` command.
Then to run the docker image use this command `docker run python-docker`

### Use of Docker
 - Here the python version will be maintained and all instances of app will execute without any dependency on python interpreter versions issues.

### TODOs
  - [x] Must make it easier to continously run `Docker` container for live results of python code changes.
  - [ ] The python packages present in venv folder must also be copied to `Docker` and eliminate recreating them or package missing issues.

**Comment by riyan-dcosta** [comment]
With the current Dev Container approach, the docker container can be run in GitHub CodeSpaces, Codespace is created in feat/flask_api branch.

**Comment by riyan-dcosta** [comment]
fix #8
